local DSC = E2Helper.Descriptions
local tKey = {"an integer", "a string"}
DSC["getPistonBase(e:n)"] = "Returns the engine base entity by "..tKey[1].." key"
DSC["getPistonBase(e:s)"] = "Returns the engine base entity by "..tKey[2].." key"
DSC["getPistonAxis(e:n)"] = "Returns shaft rotation axis by "..tKey[1].." key"
DSC["getPistonAxis(e:s)"] = "Returns shaft rotation axis by "..tKey[2].." key"
DSC["allPiston(e:)"] = "Returns the count of all piston keys"
DSC["clrPiston(e:)"] = "Clears all pistons from the E2 chip"
DSC["cntPiston(e:)"] = "Returns the count of integer piston keys"
DSC["getPiston(e:nn)"] = "Returns piston bearing timing by "..tKey[1].." key"
DSC["getPiston(e:sn)"] = "Returns piston bearing timing by "..tKey[2].." key"
DSC["getPiston(e:nv)"] = "Returns piston vector timing by "..tKey[1].." key"
DSC["getPiston(e:sv)"] = "Returns piston vector timing by "..tKey[2].." key"
DSC["getMaxPiston(e:n)"] = "Returns the piston highest point parameter by "..tKey[1].." key"
DSC["getMaxPiston(e:s)"] = "Returns the piston highest point parameter by "..tKey[2].." key"
DSC["getMinPiston(e:n)"] = "Returns the piston lowest point parameter by "..tKey[1].." key"
DSC["getMinPiston(e:s)"] = "Returns the piston lowest point parameter by "..tKey[2].." key"
DSC["remPiston(e:n)"] = "Removes the piston by "..tKey[1].." key"
DSC["remPiston(e:s)"] = "Removes the piston by "..tKey[2].." key"
DSC["setPistonSignN(e:nn)"] = "Creates a sign timed piston by "..tKey[1].." key and highest point angle in degrees"
DSC["setPistonSignN(e:sn)"] = "Creates a sign timed piston by "..tKey[2].." key and highest point angle in degrees"
DSC["setPistonWaveN(e:nn)"] = "Creates a wave timed piston by "..tKey[1].." key and highest point angle in degrees"
DSC["setPistonWaveN(e:sn)"] = "Creates a wave timed piston by "..tKey[2].." key and highest point angle in degrees"
DSC["setPistonSignV(e:nvve)"] = "Creates a cross-product timed piston with sign output by "..tKey[1].." key and highest point local vector"
DSC["setPistonSignV(e:svve)"] = "Creates a cross-product timed piston with sign output by "..tKey[2].." key and highest point local vector"
DSC["setPistonWaveV(e:nvve)"] = "Creates a cross-product timed piston with wave output by "..tKey[1].." key and highest point local vector"
DSC["setPistonWaveV(e:svve)"] = "Creates a cross-product timed piston with wave output by "..tKey[2].." key and highest point local vector"
DSC["isPistonSignN(e:n)"] = "Returns a flag if the piston is in sign mode by "..tKey[1].." key"
DSC["isPistonSignN(e:s)"] = "Returns a flag if the piston is in sign mode by "..tKey[2].." key"
DSC["isPistonWaveN(e:n)"] = "Returns a flag if the piston is in wave mode by "..tKey[1].." key"
DSC["isPistonWaveN(e:s)"] = "Returns a flag if the piston is in wave mode by "..tKey[2].." key"
DSC["isPistonSignV(e:n)"] = "Returns a flag if the piston is in cross-product sign mode by "..tKey[1].." key"
DSC["isPistonSignV(e:s)"] = "Returns a flag if the piston is in cross-product sign mode by "..tKey[2].." key"
DSC["isPistonWaveV(e:n)"] = "Returns a flag if the piston is in cross-product wave mode by "..tKey[1].." key"
DSC["isPistonWaveV(e:s)"] = "Returns a flag if the piston is in cross-product wave mode by "..tKey[2].." key"



